[phases.setup]
nixPkgs = ["python313"]

[phases.install]
cmds = ["cd api && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase complete'"]

[start]
cmd = "cd api && uvicorn index:app --host 0.0.0.0 --port $PORT"
